== Support for WildFly 14

jBPM 7.14 comes with support (and used by default) latest and greatest version of WildFly application server.
This long awaited support provides number of upgrades of libraries to allow its smooth execution.

Installation component (single zip distribution) has been also updated so it's enough to download
single zip jBPM distribution to directly take advantage of this feature.

== Query performance enhancements for displaying Process and Task variables in Manage section

In this release, changes have been made to enhance the performance of the underlying Kie Server queries responsible for
retrieving data about Process and Task variables.
If you're upgrading jBPM from a previous version, we encourage you to review the new table indexes that were introduced
in this release. You can review it in more details in https://github.com/kiegroup/jbpm/tree/master/jbpm-installer/src/main/resources/db/ddl-scripts[here].

== Multi sub forms rendering in KIE Server

Kie Server form rendering was enhanced to add forms that include lists of items (called multi sub forms in the workbench).
For more info you can https://www.youtube.com/watch?v=7pQV63LaQn4[watch this short screencast] showing the multi sub forms support in action.

== Enhanced KIE Server documentation with payload information

In addition to the above mentioned enhanced Swagger docs about the {CONTROLLER} REST API, in this release we also
improvements to Swagger docs to include payload information (examples). These are presented in the Swagger UI
and the generated documentation.

== Swagger documentation for Kie Server Controller REST API

This release includes enhanced documentation about the Kie Server Controller REST API.
You can access this documentation by running the Kie Server Controller `.war` application or jBPM Console (which contains a built-in controller).
Both applications will allow you to explore the available endpoints by accessing the `/docs` context.
Example: `http://localhost:8080/controller/docs` or `http://localhost:8080/jbpm-console/docs`.

A static version of the API is also available at http://jbpm.org/learn/documentation.html[jbpm.org].

== ElasticSearch event emitter for runtime events

Added out of box support for a new event emitter that pushes data out to ElasticSearch.
This enables process data to be pushed and stored in ElasticSearch.

== Filtering capabilities for Process Instance Logs

In this release, we have enhanced the Process Instance Logs view by introducing filtering capabilities that allow users
to narrow down the timeline results according to their needs. There are now two new filter categories that allows a user
to filter process instances based on event types such as either Node Entered or Node Completed or process nodes, such as
Human Task, Start and End nodes, and so on.

Apart from the filtering enhancements, users can now also view extra details about Human Task nodes, such as State,
Owner, Description, and so on.
