== View task comments in Work tab
You can now add and view task-related comments in the *Work* tab of tasks in Business Central. This enhancement creates more streamlined workflow and collaboration around tasks.

To enable or disable this feature, you can select or clear the *Show
 task comments at work tab* parameter in the process administration settings in Business Central.

You cannot add comments to tasks in a *Completed* state and you cannot delete comments added by other users.

== New chart API for Business Central

Business Central uses a new API for chart rendering based on C3 and D3.
The C3 Renderer API is used by default and implements all of the features from the previous chart library, Google Charts.
The Google Charts library is now deprecated and removed from Business Central.
To revert to Google Charts,  build it from sources and add it to Business Central (see the https://github.com/kiegroup/appformer/tree/master/dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-google[`README.md`] file in `dashbuilder-renderer-google`), and then set the renderer system property to `org.dashbuilder.renderer.default=gwtcharts`.