== Installation of work items directly from service repository

Service repository that has been improved a lot over the last two releases received another feature - install work items into existing workbench.
This then allows to have the project directly prepared for work items without a need to install it from within jBPM designer.

To read more have a look at http://mswiderski.blogspot.com/2018/07/easy-workitem-installation-jbpm.html[this article].

'''

== Running the service repository on Heroku

Another feature added to the service repository was the ability to deploy the springboot repository war on Heroku.

For more information see https://github.com/kiegroup/jbpm-work-items/blob/master/repository-springboot/README.md#running-the-repository-on-heroku[this documentation]

'''

== Service repository rest service

When using the sevice repository springboot or wildfly deployments in addition to the numerous workitems hosted users
now have a rest api available to query information about these workitems.

'''

== SpringBoot jBPM auto configuration update

SpringBoot auto configuration for jBPM (and KIE Server that uses jBPM extension) has been improved to allow to use custom entities as part
of the EntityManagerFactory used by the execution engine. That enables colocation of business logic and business assets.

It's enough to provide a bean that will override entityManagerFactory bean that comes with jBPM auto configuration.

'''

== Creation of indexes for all database tables

With the update to JPA 2.1 all jBPM entities received an update to declare index creation information.
This results in a better query performance overall.

'''
