=  About jBPM
:awestruct-layout: rightcol
/ rightcol_partial: rightcol-downloads.html.haml
:showtitle:

== What does jBPM do?
A business process allows you to model your business goals by describing the steps that need to be executed to achieve that goal and the order, using a flow chart.  This greatly improves the visibility and agility of your business logic, results in higher-level and domain-specific representations that can be understood by business users and is easier to monitor.
The core of jBPM is a light-weight, extensible workflow engine written in pure Java that allows you to execute business processes using the latest BPMN 2.0 specification.  It can run in any Java environment, embedded in your application or as a service.
On top of the core engine, a lot of features and tools are offered to support business processes throughout their entire life cycle:

* Eclipse-based and web-based editor to support the graphical creation of your business processes (drag & drop).
* Pluggable persistence and transactions based on JPA / JTA.
* Pluggable human task service based on WS-HumanTask 'for' including tasks that need to be performed by human actors.
* Management console supporting process instance management, task lists and task form management, and reporting.
* Optional process repository to deploy your process (and other related knowledge).
* History logging (for querying / monitoring / analysis).
* Integration with Seam, Spring, OSGi, etc.


BPM makes the bridge between business analysts, developers and end users, by offering process management features and tools in a way that both business users and developers like it.  Domain-specific nodes can be plugged into the palette, making the processes more easily understood by business users. 
jBPM supports adaptive and dynamic processes that require flexibility to model complex, real-life situations that cannot easily be described using a rigid process.  We bring control back to the end users by allowing them to control which parts of the process should be executed, to dynamically deviate from the process, etc. 
jBPM is also not just an isolated process engine.  Complex business logic can be modeled as a combination of business processes with business rules and complex event processing.  jBPM can be combined with the Drools project to support one unified environment that integrates these paradigms where you model your business logic as a combination of processes, rules and events.

== Process languages
jBPM is based on a generic process engine, which is our foundation to support multiple process languages natively.  jBPM5 focusses on BPMN 2.0 as the language for expressing business processes.  BPMN 2.0 is a standardized specification that defines a visualization and XML serialization of business processes, and can be extended (if necessary) to include more advanced features.

=== jBPM6

jBPM6 is the latest community version of the jBPM project.  It is based on the BPMN 2.0 specification and supports the entire life cycle of the business process (from authoring through execution to monitoring and management).

It offers open-source business process execution and management, including:

* Embeddable, lightweight Java process engine, supporting native BPMN 2.0 execution.
* Human interaction using an independent WS-HT task service.
* BPMN 2.0 process modeling in Eclipse (developers) and the web (business users).
* Web tooling to model, deploy, execute and monitor your processes, including for example a data and form modeler, simulation, deployment, task lists, etc.
* Web-based business activity monitoring and reporting that allows you to define your own reports.
* Managing and deploying your processes using technologies underneath like Git and Maven.
* An execution server that you can remotely connect to (REST, JMS) and can be deployed in a clustered environment for load balancing and high availability.
* Tight, powerful integration with business rules and event processing.

=== What to do if I encounter problems or have questions?
You can always contact the jBPM community for assistance.

* Email: jbpm-dev@lists.jboss.org[jbpm-dev@lists.jboss.org] (note that you have to https://lists.jboss.org/mailman/listinfo/jbpm-dev[subscribe] to the list first before being able to post)
* IRC: #jbpm at chat.freenode.net
* http://community.jboss.org/en/jbpm?view=discussions[jBPM User Forum]
    
'''