= Source code
:awestruct-layout: base
:linkattrs:
:showtitle:

We use http://git-scm.com/[Git] to manage our source code. The reference repositories are on GitHub:

http://github.com/droolsjbpm[http://github.com/droolsjbpm]

To build our sources, follow the instructions https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/blob/master/README.md[in the README file in droolsjbpm-build-bootstrap].

To learn more about git, read the free book http://progit.org/book/[Git Pro].

== jBPM repository

Most of the core jBPM services are located in the jBPM repository.

https://github.com/droolsjbpm/jbpm[jBPM, role=lead]::
_The source code for jBPM itself, examples and documentation._

. Get the source code locally with http://git-scm.com/[Git]:
+
----
 $ git clone git@github.com:droolsjbpm/jbpm.git
 ...
----
+
If you don't have a GitHub account or your local Git installation isn't configured with it,
use this command instead, to avoid an authentication issue:
+
----
 $ git clone https://github.com/droolsjbpm/jbpm.git jbpm
 ...
----

. Build it with http://maven.apache.org/[Maven]:
+
----
 $ cd jbpm
 $ mvn clean install -DskipTests
 ...
----
+
The first time, Maven might take a lot time, because it needs to download jars.

== Tracking our changes

It's easy to keep an eye on the source code changes on the project:

* Go to the https://github.com/droolsjbpm/repositories[GitHub website].
* Click on the repository you're intrested in
* Click on the link Commits to show the commit history.
* You can subscribe to that feed with the orange feed icon link.

== Website

https://github.com/droolsjbpm/jbpm-website[jbpm-website, role=lead]::
_The source code for this website and presentations._

. Get the source code locally with http://git-scm.com/[Git]:
+
----
 $ git clone git@github.com:droolsjbpm/jbpm-website.git
 ...
----

. Build it with http://awestruct.org/[Awestruct]:
+
----
 $ cd jbpm-website
 $ ./build.sh clean build
 ...
----

. Show it in a browser:
+
----
 $ firefox _site/index.html
 ...
----

. Edit the http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc] sources.

Want to improve our sources? *Pull requests are welcome!*
