== Explore your running environment

*jBPM console*

jBPM Console (aka workbench) provides feature rich authoring and management environment. It consists of:

- Design perspectives where users can create projects and pages
- Deploy perspectives where users can manage execution servers
- Manage perspectives where users can take control over process and case instances
- Track perspectives where users can access assigned tasks and reports

jBPM Console can be accessed (once the server was started) at http://localhost:8080/jbpm-console[*http://localhost:8080/jbpm-console*]

There are set of predefined users that can be used to directly logon to jBPM Console:

- wbadmin/wbadmin
- krisv/krisv
- john/john
- mary/mary
- katy/katy
- jack/jack
- kieserver/kieserver1!

Additional users can be created via jBPM Console Admin section.

'''

*KIE Server Swagger documentation*

KIE Server is the execution server that provides various capabilities

- BRM (business rules)
- BPM (business processes)
- BRP (planning/solver)
- Case Management
- DMN (decisions)

Its complete REST api documentation can be accessed at http://localhost:8080/kie-server/docs[*http://localhost:8080/kie-server/docs*]

'''

*jBPM Case Management Showcase*

jBPM Case Management Showcase is a web application that aims at illustrating various case management building blocks in action. These
are UI components built on top of KIE Server REST api for case management. It's not intended for production usage but more for getting better
understanding of the capabilities.
Case management, in general should be business focused so generic UI won't provide much business context to the knowledge workers.

jBPM Case Management application can be accessed at http://localhost:8080/jbpm-casemgmt[*http://localhost:8080/jbpm-casemgmt*]

Same users as for jBPM Console can be used to logon to this application.

'''

*jBPM Service Repository*

jBPM Service Repository application delivers community work items - domain specific services (such as Twitter, Jira, Github and more)
so they can be easily used (by drag and drop) when designing your process and case definitions.

jBPM Service Repository application can be accessed at http://localhost:8080/repository[*http://localhost:8080/repository*].
Same URL can be used from within jBPM designer to import these domain specific services.

'''


== Try examples

Once you get yourself familiar with the tools of the jBPM it's time to see something running. The easiest way is to try one of the examples
shipped with the platform, it will show typical path users take to design, build and execute business logic.

=== Evaluation process


[cols="8a,4a", frame=none]
|===
|Evaluation process is a business process that is human centric (heavily uses human actors to perform work) that defines a complete flow of
activities to perform employee evaluation. This examples shows:

- importing example project
- building and deploying project
- verifying deployment to execution server
- executing process instance and work with human tasks
- exploring reporting capabilities

|video::-fxL2iioPRI[youtube]
|===

'''

=== IT Orders case

[cols="8a,4a", frame=none]
|===
|IT Orders case is more advanced use of the jBPM that relies on dynamic nature of business problems. It allows to take actions based on
data so it's more event/data driven than structured processes. Although it still allows users to take advantage of process fragments
to express bit of workflows within the case. This examples shows:

* importing example project
* building and deploying project
* verifying deployment to execution server
* use of jBPM Case management Showcase application
* document upload and handing
* monitoring of case instance in jBPM Console

More about case management capabilities can be found in following articles

- http://mswiderski.blogspot.com/2016/10/case-management-jbpm-v7-part-1.html[Introduction to jBPM Case Management]
- http://mswiderski.blogspot.com/2016/10/case-management-jbpm-v7-part-2-working.html[Working with case data]
- http://mswiderski.blogspot.com/2016/10/case-management-jbpm-v7-part-3-dynamic.html[Working with dynamic activities]

|video::jtYY5jVD9T0[youtube]
|===

'''

== Build your project from scratch

[cols="8a,4a", frame=none]
|===
|Building new project from scratch can give you an option to have a clean start where you design your process or case
to fit your needs. This example shows:

* creating new project
* creating new asset - business process
* build and deploy to execution server
* execute process instance

|video::pdgj0hrF5rc[youtube]
|===

'''